import { Diamond } from './types';

export const ovalDiamonds: Diamond[] = [
  {
    id: 'oval-001',
    carat: 2.47,
    shape: 'oval',
    color: 'H',
    clarity: 'VS1',
    cut: 'RC Ideal Cut',
    price: 2280,
    compValue: 3420,
    qualityScore: 15,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 92,
    sparkleScore: 88,
    valueScore: 90,
  },
  {
    id: 'oval-002',
    carat: 2.31,
    shape: 'oval',
    color: 'G',
    clarity: 'VS1',
    cut: 'RC Ideal Cut',
    price: 2280,
    compValue: 3250,
    qualityScore: 15,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 82,
    sparkleScore: 96,
    valueScore: 84,
  },
  {
    id: 'oval-003',
    carat: 2.58,
    shape: 'oval',
    color: 'I',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 2180,
    compValue: 3280,
    qualityScore: 14,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 98,
    sparkleScore: 80,
    valueScore: 88,
  },
  {
    id: 'oval-004',
    carat: 2.35,
    shape: 'oval',
    color: 'H',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 2050,
    compValue: 3120,
    qualityScore: 14,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 84,
    sparkleScore: 85,
    valueScore: 98,
  },
  {
    id: 'oval-005',
    carat: 2.19,
    shape: 'oval',
    color: 'F',
    clarity: 'VVS2',
    cut: 'RC Ideal Cut',
    price: 2380,
    compValue: 3580,
    qualityScore: 15,
    priceScore: 'Good',
    certified: 'GIA',
    hasVideo: true,
    caratScore: 72,
    sparkleScore: 99,
    valueScore: 70,
  },
  {
    id: 'oval-006',
    carat: 2.44,
    shape: 'oval',
    color: 'H',
    clarity: 'SI1',
    cut: 'Excellent',
    price: 1890,
    compValue: 2760,
    qualityScore: 12,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: false,
    caratScore: 90,
    sparkleScore: 74,
    valueScore: 94,
  },
  {
    id: 'oval-007',
    carat: 2.62,
    shape: 'oval',
    color: 'J',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 2100,
    compValue: 3050,
    qualityScore: 13,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 99,
    sparkleScore: 76,
    valueScore: 92,
  },
];

export const roundDiamonds: Diamond[] = [
  {
    id: 'round-001',
    carat: 1.42,
    shape: 'round',
    color: 'G',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 1720,
    compValue: 2580,
    qualityScore: 15,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 85,
    sparkleScore: 95,
    valueScore: 90,
  },
  {
    id: 'round-002',
    carat: 1.51,
    shape: 'round',
    color: 'H',
    clarity: 'VS1',
    cut: 'RC Ideal Cut',
    price: 1780,
    compValue: 2650,
    qualityScore: 15,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 94,
    sparkleScore: 88,
    valueScore: 88,
  },
  {
    id: 'round-003',
    carat: 1.38,
    shape: 'round',
    color: 'F',
    clarity: 'VS1',
    cut: 'RC Ideal Cut',
    price: 1820,
    compValue: 2720,
    qualityScore: 15,
    priceScore: 'Good',
    certified: 'GIA',
    hasVideo: true,
    caratScore: 78,
    sparkleScore: 98,
    valueScore: 78,
  },
  {
    id: 'round-004',
    carat: 1.57,
    shape: 'round',
    color: 'I',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 1650,
    compValue: 2480,
    qualityScore: 14,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 96,
    sparkleScore: 82,
    valueScore: 95,
  },
];

export const cushionDiamonds: Diamond[] = [
  {
    id: 'cushion-001',
    carat: 2.12,
    shape: 'cushion',
    color: 'H',
    clarity: 'VS1',
    cut: 'RC Ideal Cut',
    price: 1850,
    compValue: 2780,
    qualityScore: 15,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 88,
    sparkleScore: 86,
    valueScore: 92,
  },
  {
    id: 'cushion-002',
    carat: 2.34,
    shape: 'cushion',
    color: 'G',
    clarity: 'VS2',
    cut: 'RC Ideal Cut',
    price: 2050,
    compValue: 3100,
    qualityScore: 14,
    priceScore: 'Great',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 96,
    sparkleScore: 90,
    valueScore: 88,
  },
  {
    id: 'cushion-003',
    carat: 1.98,
    shape: 'cushion',
    color: 'F',
    clarity: 'VVS2',
    cut: 'RC Ideal Cut',
    price: 2180,
    compValue: 3250,
    qualityScore: 15,
    priceScore: 'Good',
    certified: 'IGI',
    hasVideo: true,
    caratScore: 76,
    sparkleScore: 97,
    valueScore: 72,
  },
];

export function getDiamondsByShape(shape: string): Diamond[] {
  switch (shape) {
    case 'oval': return ovalDiamonds;
    case 'round': return roundDiamonds;
    case 'cushion': return cushionDiamonds;
    default: return ovalDiamonds;
  }
}

export function getDiamondById(id: string): Diamond | undefined {
  return [...ovalDiamonds, ...roundDiamonds, ...cushionDiamonds].find(d => d.id === id);
}
